# Generated by Django 5.2.7 on 2025-10-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
    ]
